site_name: Edge AI Trust Project
site_url: https://chirag-indi.github.io/edgeAI/
repo_url: https://github.com/chirag-indi/edgeAI
theme: readthedocs

extra_css:
  - css/theme_extra.css


markdown_extensions:
  - admonition